import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <link
          href="https://styleguide.brainly.com/225.8.0/style-guide.css"
          rel="stylesheet"
        />
        <Script src="https://styleguide.brainly.com/images/icons-f71af3176e.js" />
      </body>
    </html>
  );
}
